fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      # for future parser tests with puppet < 4
      ref: "4.25.1"
    alternatives:
      repo: "https://github.com/voxpupuli/puppet-alternatives"
      # for tests with puppet < 4
      ref: "v1.0.1"
    hadoop_lib: "https://github.com/MetaCenterCloudPuppet/cesnet-hadoop_lib"
  symlinks:
    impala: "#{source_dir}"
