fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    alternatives: "git://github.com/puppet-community/puppet-alternatives"
    hadoop_lib: "https://github.com/valtri/cesnet-hadoop_lib"
  symlinks:
    impala: "#{source_dir}"
